"""empty message

Revision ID: 41b7f9974ab5
Revises: 50b8c365bc99
Create Date: 2016-08-10 00:17:53.987688

"""

# revision identifiers, used by Alembic.
revision = '41b7f9974ab5'
down_revision = '50b8c365bc99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stockitem', sa.Column('totalprice', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stockitem', 'totalprice')
    ### end Alembic commands ###
