"""empty message

Revision ID: 50b8c365bc99
Revises: a9abb95bc5b8
Create Date: 2016-08-08 21:58:47.434252

"""

# revision identifiers, used by Alembic.
revision = '50b8c365bc99'
down_revision = 'a9abb95bc5b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stockitem', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stockitem', 'job', ['job_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stockitem', type_='foreignkey')
    op.drop_column('stockitem', 'job_id')
    ### end Alembic commands ###
