"""empty message

Revision ID: 92ee03b0bc3f
Revises: 686bd0b2354d
Create Date: 2016-08-06 22:56:51.361618

"""

# revision identifiers, used by Alembic.
revision = '92ee03b0bc3f'
down_revision = '686bd0b2354d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('active', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'active')
    ### end Alembic commands ###
