"""empty message

Revision ID: f9b62a8502d2
Revises: 41b7f9974ab5
Create Date: 2016-08-15 00:15:53.899422

"""

# revision identifiers, used by Alembic.
revision = 'f9b62a8502d2'
down_revision = '41b7f9974ab5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stockitem', sa.Column('writeoff', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stockitem', 'writeoff')
    ### end Alembic commands ###
